# Specify model input directory
input:
  dir: "data"
  image_shape: [64, 64]

# Specify the training data to be used for the model
model:
  channels: 3
  height: 64
  width: 64
  latent_dim: 64
  batch_size: 20
  iterations: 10000
  start: 1

# Specify output file 
output: 
  dir: "outputs"
